- name: bleep-setup-action
  # You may pin to the exact commit or the version.
  # uses: bleep-build/bleep-setup-action@0a7ee84e9b61bf535f77af61921d92efaf01081d
  uses: bleep-build/bleep-setup-action@0.0.2
